### ISSUE TITLE
Set Language at runtime

### ISSUE THREAD

**Issue by reni99** [stefalda/ReactNativeLocalization#48]
Hi there :)
Is it possible to set the language in one screen for the hole application? I have the problem that I manually force set the language in a settings screen with setLanguage(), but this only applies to the current screen. So when I change to another screen, the language falls back to the default language. Thank you for any help!

**Comment by stefalda** [comment]
Maybe you could handle some sort of notification or global language state to fix the issue...

**Comment by flavordaaave** [comment]
I do have a global state for the language but how would this work? I'd still have to call `setLanguage()` in every component when the global state updates, right?

I also tried to implement a small native module to switch the language:
```
#import "LanguageSwitcher.h"
#import "RCTLog.h"

@implementation LanguageSwitcher

RCT_EXPORT_MODULE();

RCT_EXPORT_METHOD(switch:(NSString *)languageCode)
{
  RCTLogInfo(@"Switch language to %@", languageCode);
  [[NSUserDefaults standardUserDefaults] setObject:[NSArray arrayWithObjects:languageCode, nil] forKey:@"AppleLanguages"];
}
@end
```

But unfortunately the setting is not applied directly so the user needs to restart the app in order to have the new language applied. There might be a native method to force a reload of the react-native app which can be used here but so far I haven't found anything like this...

**Comment by zeljkoX** [comment]
In order to change language globally every screen needs to be updated. 
Below example provides you with HOC  LanguageProvider. By changing language using LanguageProvider api every connected screen will be updated.

[LanguageProvider example](https://github.com/zeljkoX/react-native-localization-example
)

**Comment by mklb** [comment]
Try it like this: Pass the String object down from your router so every view references this.props.strings. Refresh the current view, all others should be updated

**Comment by twairball** [comment]
@stefalda Seems that `react-native-localization` doesn't respect `AppleLanguages` for iOS or `locale_override` for android?

**Comment by stefalda** [comment]
It should have been fixed by [PR81](https://github.com/stefalda/ReactNativeLocalization/pull/81)

**Comment by 404sand808s** [comment]
Hi, I've started using this component and it's fantastic. Also looking for a solution for runtime language selection though. Tried to pass the string down as a prop but it doesn't seem to allow modifying it at the individual component level (i.e. pass down the String object that's had it's language set, and then set the language keys in each component so that it can display what we need to). Setting all the keys upstream wouldn't work of course since there are about a hundred components that would make use of it. Has anybody else found the best solution for this? Thanks.

**Comment by zjkuang** [comment]
Switching language does not happen often. I simply force exit the app.

yarn add react-native-exit-app

import RNExitApp from 'react-native-exit-app';

  Alert.alert(
    'ATTENTION',
    'Language has been changed. App needs to restart to make the change effective. Ready to exit the app?',
    [
      {
        text: 'YES',
        onPress: () => {
          RNExitApp.exitApp();
        },
        style: 'default',
      },
      {
        text: 'Later',
        style: 'cancel',
      },
    ],
  );
