### ISSUE TITLE
when link the library to my project. the app build failed

### ISSUE THREAD

**Issue by ayyoobcastro** [stefalda/ReactNativeLocalization#71]
I installed the this library after I run react-native link ReactNativeLocalization. the I build my app but it fails . Can you help me t fix this issue.

**Comment by stefalda** [comment]
Have you tried restarting everything?
What error do you get?

**Comment by vessp** [comment]
1. npm install --save react-native-localization
2. react-native link react-native-localization
3. Try to open MyProject.xcodeproj in XCode
4. Error Popup: 'Project XX/XX/MyProject.xcodeproj cannot be opened because the project file cannot be parsed.'
5. react-native unlink react-native-localization
6. `rnpm-install info Unlinking react-native-localization android dependency 
rnpm-install info Android module react-native-localization has been successfully unlinked 
rnpm-install info Unlinking react-native-localization ios dependency 
rnpm-install ERR! It seems something went wrong while unlinking. Error: searchPaths.filter is not a function 

searchPaths.filter is not a function
`

**Comment by mhdayyoob** [comment]
I linked the file and restart My xcode the run my app. but the error still exist

**Comment by mhdayyoob** [comment]
![screen shot 2017-04-06 at 11 26 12 pm](https://cloud.githubusercontent.com/assets/16235674/24788108/932069e6-1b20-11e7-99c2-bf1add49981b.png)


this is  a screenshot of the error that I am getting

**Comment by stefalda** [comment]
What version of XCode are you using and what version of iOS are you targeting?

**Comment by mhdayyoob** [comment]
my xcode version is 7.3.1 and my iOS target is above 9  . please help me to fix this

**Comment by stefalda** [comment]
I've just tried to create a new project and everything went smoothly... sorry but I'm unable to reproduce it...
